### ISSUE TITLE
Chat goes offscreen on mobile

### ISSUE THREAD

**Issue by sharife** [eternagame/eternagame.org#129] opened 2020-05-20 05:21 UTC
The chat doesn’t resize properly on mobile, causing the width of the text and input area to exceed the width of the container.

**Comment by AlexHalb** [comment] 2020-05-20 19:41
@sharife Could you give some steps to reproduce? I'm not seeing this on my own mobile device or on devtools.

**Comment by aminere** [comment] 2020-05-20 23:33
@AlexHalb here are some screenshots from Sharif - is this something you can work on?
iPhone XR website: https://files.slack.com/files-pri/T7SAV7LAD-F01460FG2VA/image_from_ios.png
iPhone XR game: https://files.slack.com/files-pri/T7SAV7LAD-F013YDT5B8V/image_from_ios.png

**Comment by AlexHalb** [comment] 2020-05-21 01:51
This is something I can work on. However, I can't view those because I'm not in the Stanford University slack. Could you perhaps download them and upload them here via GitHub or send them some other way?

**Comment by aminere** [comment] 2020-05-21 02:08
Yes, here they are. I'm here if you need anything, thank you!
**iPhone XR website** 
![image](https://user-images.githubusercontent.com/11358110/82515433-36287c80-9ae6-11ea-9b23-12062928330f.png)
**iPhone XR game**
![image](https://user-images.githubusercontent.com/11358110/82515442-3c1e5d80-9ae6-11ea-96a5-efc0c54354db.png)

**Comment by AlexHalb** [comment] 2020-05-21 02:13
Thank you. I'll get started.

**Comment by AlexHalb** [comment] 2020-05-21 03:15
This is a strange issue. For some reason, it won't appear on Chrome or Safari dev tools. I believe the browser in the images is Chrome. I ended up using the iOS simulator to view the page. Although I didn't experience the overflow to the same degree, it is there and it is an issue. Unfortunately, the iOS simulator was slowing down my computer to the point where I couldn't do much. Perhaps later I can reopen and try again without having these issues.

**Comment by AlexHalb** [comment] 2020-05-21 16:45
I'm fairly confident to fix the issue, you just need to zoom out, and then it won't go back when you reload. I think it's related to the `<meta name="viewport" content="width=device-width, initial-scale=1.0">` tag.

**Comment by AlexHalb** [comment] 2020-05-21 16:55
Turns out this issue goes deeper than just the chat; when I load the landing page on mobile Chrome, it does the same thing. However, resizing works there too. I'm assuming this applies to all pages until they are resized. This is really hard to test because once I've zoomed out, it fixes the issue until I clear all website data! Again, I'm not sure what exactly the issue is, but I suspect a bit of CSS is behaving strangely and overriding the `<meta name="viewport>"` tag. I'll look into it further.

**Comment by aminere** [comment] 2020-05-21 18:04
Excellent investigation, thanks a lot @AlexHalb! If you are stuck at any point, I'll be happy to look at it too after I'm done with some features I'm working on. 
About the viewport meta, I think it makes sense to disable the zoom with `user-scalable=no` because the website is already supposed to be responsive. Like this:
`<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">`

**Comment by luxaritas** [comment] 2020-05-21 18:12
I do not recommend this - visually impaired users in particular may still want to magnify it.

Also fwiw, this has always happened with the chat on mobile since I made it years ago - the rest of the site just wasn’t mobile performant so it wasn’t something I ever dug into (in addition to the fact that it only ever happened on physical mobile devices)

**Comment by luxaritas** [comment] 2020-05-21 18:14
I do have a suspicion that this has something to do with how width is calculated in iframes, but I don’t know what specifically that would be

**Comment by AlexHalb** [comment] 2020-05-21 19:09
What's strangest to me is how when you zoom out, it is fixed and doesn't come back. Makes it really hard to identify.

**Comment by aminere** [comment] 2020-05-21 19:12
Fair enough @luxaritas! I suspect there is a lot of legacy code that might not be necessary but is interfering and making the investigation difficult. The chat is a simple list container, if this persists, it might be better to wipe a large part of the layout and apply only the necessary styling.

**Comment by AlexHalb** [comment] 2020-05-27 19:24
I'm going to need someone else to look into this one. I've seemingly 'run out of tries' and can't view the issue. I can't do anything to reproduce it and have no way to fix it either. However, most mobile users would zoom out on the initial page load anyway and fix the issue without consciously noticing there was a bug anyway, so it won't interfere very much with the site anyway.

**Comment by aminere** [comment] 2020-05-27 19:57
No problem, thanks a lot @AlexHalb for your time investigating this !! I can take a look soon.

**Comment by luxaritas** [comment] 2020-06-10 04:25
Hopefully this should be resolved with a recent deployment of eternagame/HTML-chat

**Closed by luxaritas** 2020-06-10 04:25 UTC
Labels: High Priority, bug
